import "./globals.css";

export const metadata = {
  title: "PerfettoFood - Izohlar",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="uz">
      <body className={``}>
        {children}
      </body>
    </html>
  );
};