import { Bounce, ToastContainer } from "react-toastify";
import "./globals.css";

export const metadata = {
  title: "PerfettoFood - Izohlar",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="uz">
      <body className={``}>
        <ToastContainer
          position="top-right"
          autoClose={5000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="colored"
          transition={Bounce}
        />
        {children}
      </body>
    </html>
  );
};